export const siteConfig = {
  name: "Tarek Okasha",
  title: "Tarek Okasha — AI Systems & Custom Software",
  description:
    "Independent engineer in Cairo. AI systems, intelligent automations, and custom software for founders and operators. Currently booking projects.",
  url: "https://tarekokasha.com",
  email: "tarekokasha53@gmail.com",
  whatsapp: "+201131701911",
  whatsappLink: "https://wa.me/201131701911",
  linkedin: "https://www.linkedin.com/in/tarek-okasha-1710811b8",
  location: "Cairo, Egypt — Remote",
  availability: "Currently booking projects",
  tagline: "Software that pays for itself.",
  subtagline: "AI systems, internal tools, and automations — engineered with the discipline of robotics and shipped in weeks. Real software that runs in production without you watching it.",
} as const;

export const navLinks = [
  { label: "Work", href: "/work" },
  { label: "About", href: "/about" },
  { label: "Contact", href: "/contact" },
] as const;

export const projects = [
  {
    slug: "aurevia",
    client: "Aurevia",
    title: "AI photography studio for a Dubai jewelry brand",
    oneLineOutcome: "Collapsed a 2-week production cycle into 24 hours.",
    year: 2025,
    tags: ["AI", "Automation", "Internal Tools"],
    featured: true,
    order: 1,
    image: "/images/aurevia.png",
    liveUrl: "https://aurevia-website-orcin.vercel.app",
  },
  {
    slug: "ai-automations",
    client: "Shae Group",
    title: "70+ AI automations for enterprise operations teams",
    oneLineOutcome: "Eliminated 40+ hours of weekly manual work across both organizations.",
    year: 2025,
    tags: ["AI Automations", "n8n", "LLM"],
    featured: false,
    order: 4,
    image: "/images/automation.png",
    liveUrl: "",
  },
  {
    slug: "al-helaly-erp",
    client: "Al-Helaly Constructions",
    title: "Custom ERP system for a mid-size construction company",
    oneLineOutcome: "Replaced 14 spreadsheets with one system. Projects stopped running late.",
    year: 2024,
    tags: ["ERP", "Custom Software", "Operations"],
    featured: false,
    order: 5,
    image: "/images/erp.png",
    liveUrl: "https://helaly-erp.vercel.app",
  },
  {
    slug: "sportix-smis",
    client: "Sportix",
    title: "Sports Management Information System for Saudi sports clubs",
    oneLineOutcome: "Unified operations for 8 clubs across 3 sports federations.",
    year: 2024,
    tags: ["SMIS", "Sports Tech", "Custom App"],
    featured: true,
    order: 2,
    image: "/images/smis.png",
    liveUrl: "https://sportix-smis.vercel.app",
  },
  {
    slug: "robotics-arm",
    client: "Robotics R&D",
    title: "Voice-controlled UR5e pick-and-place robot",
    oneLineOutcome: "A UR5e arm that finds, grips, and places objects on a spoken command — end to end.",
    year: 2025,
    tags: ["Robotics", "ROS 2", "Computer Vision"],
    featured: true,
    order: 3,
    image: "/images/robotics.png",
    liveUrl: "",
  },
] as const;
